name: Stu
favicon: null
layout_spectrum: 0.6016631051898003
typography_spectrum: 0.9998566643334925
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4143619812093675
  lightness: 0.04915666347369552
  saturation: 0.2625350006856024
  rhythmicContrast: 0.38373983930796385
purpose: []
